### PR TITLE
checking on an undefined snmpid, do not include those into the mrtg conf...

### PR DESCRIPTION
**Pull request by fooelisa**
belts and braces barryo :)

### CODE REVIEW

**Comment by barryo** [comment]
Hey @fooelisa! I'm not sure the following test is the best:

```php
if( $port->ifnameToSNMPIdentifier() )
```

That function just sanitises the ifname for MRTG. If I understand correctly, you have cases where there is no `ifname`? If so, the test would be better written as:

```php
if( $port->getIfName() )
```

This would evaluate as false for null and empty string.

 - Barry

**Comment by fooelisa** [comment]
You are absolutely right, they don't have a name. When I entered the interfaces I put in something called name, but on second glance it seems like this became the "name" not the "ifName" in the DB. This works for me! Thanks

**Comment by barryo** [comment]
Done. 

> When I entered the interfaces I put in something called name

We should really remove the code that allows you to add ports manually. This only leads to problems. Ports should be discovered and added:

 - when adding the switch by SNMP discovery
 - as part of a [cron script](https://github.com/inex/IXP-Manager/wiki/Updating-Switches-and-Ports-via-SNMP) that re-discovers switches routinely.

**Comment by fooelisa** [comment]
Agreed, although, It came in handy in my case for a reseller port who I entered and assigned a fake interface for. Not having an interface broke the brid config generation, which could probably use some love in this scenario as well.

**Pull request closed without merging**
