### PR TITLE
Add field to the interface for peeringmacrov6

### PR DESCRIPTION
**Pull request by rowanthorpe**
This (hopefully) adds control of the peeringmacrov6 to the interface. I just made these changes by blasting through all the places peeringmacro occurs, and where appropriate mirroring code for it with equivalent peeringmacrov6 code, so there is a chance I've missed something. I didn't test it yet, and if you'd prefer I do testing first, I will try to get to it later. I guess travis should catch any obvious ommission anyway.

### CODE REVIEW

**Comment by rowanthorpe** [comment]
This (hopefully) solves to #212

**Comment by rowanthorpe** [comment]
If accepted this includes a string validation which #214 should also modify if accepted (it doesn't yet obviously).

**Comment by rowanthorpe** [comment]
...I updated the commit to include 'UTF-8' param in the stringLength validation. I think this PR is still missing something though. Haven't had chance to test yet.

**Comment by barryo** [comment]
@rowanthorpe - apologies, I coded this up as per the commit in #212 before I noticed this PR.

**Pull request closed without merging**
