### PR TITLE
Add PHP 7.1 and 7.2 to Travis test matrix

### PR DESCRIPTION
**Pull request by emirb**
[NF] Adds two more recent PHP versions to Travis CI

### CODE REVIEW

**Comment by barryo** [comment]
Hi @emirb - thanks for this but we before we can accept a patch, we need contributors to sign the CLA - please see the [submitting changes section here](https://github.com/inex/IXP-Manager/blob/master/CONTRIBUTING.md#submitting-changes).

Thanks,
Barry

**Comment by emirb** [comment]
Thanks @barryo , I didn't fully read the contributing guidelines. I've signed the CLA and sent it.

**Comment by barryo** [comment]
btw, working tests: https://travis-ci.org/inex/IXP-Manager/builds/353037692

**Comment by emirb** [comment]
Great! I just wanted to ensure beforehand that composer dependencies all installable on all 7.x versions. Looking forward to v5!

**Pull request merged**
