### PR TITLE
fixing nits

### PR DESCRIPTION
**Pull request by fooelisa**
Just a few things I figured could be useful: added 40 and 100G interfaces to drop down menus, chmod on an executable to actually be executable, don't offer unset interfaces in drop down menu.... stay tuned

### CODE REVIEW

**Comment by barryo** [comment]
All fine @fooelisa but can you roll back @7366039  - allowing the select of *unset* interfaces is a convenience that will add a world of pain *(by way of questions to the mailing list)* if removed.

**Comment by fooelisa** [comment]
OK, might have been a little drastic measure for my problem. Instead I adapted the documentation at: https://github.com/inex/IXP-Manager/wiki/Switch%20and%20Switch%20Port%20Management 
"""
Port Types

Switch ports are assigned types as defined here. This is important as, for example, only peering ports are offered as an option when assigning a port to a physical interface.
==>
Switch ports are assigned types as defined here. This is important as, for example, only ports of the type peering or undefined are offered as an option when assigning a port to a physical interface. 
"""
It led me to believe only peering would be selectable in the menu, and with a large amount of empty ports I ended up REALLY wanting to exclude the unassigned as suggested. 

How is that?

**Comment by barryo** [comment]
Better :smiley:

**Comment by listerr** [comment]
We have a few where they are technically "Other" i.e. they are not
peering ports and are not billable as such. (they are either temporary
or out-of-band connection arrangements etc.)

Also it may well be worth testing this doesn't break the resold port
capability as these are set to "Fanout" or some such, but I haven't
worked out when it gets that particular type.

Another good feature would be to understand the media type offered by
the port (e.g., copper / fibre etc.) as one FAQ we get is

"Which one of these ports are fibre and which are copper?"

It's possible to work it out from the port descriptions from the device
IF you know what to look for, but would be better if we could make that
clearer.

Also we're offering a range of different wavelength optics /
Bidirectional optics and it would be good to record that somewhere the
customer can see rather than hidden in the port notes.

Rob



On Fri, Jan 16 at 9:05:31 PM, Elisa Jasinska wrote:

> OK, might have been a little drastic measure for my problem. Instead
> I adapted the documentation at:
> https://github.com/inex/IXP-Manager/wiki/Switch%20and%20Switch%20Port%20Management
> """
> Port Types
> Switch ports are assigned types as defined here. This is important
> as, for example, only peering ports are offered as an option when
> assigning a port to a physical interface.
==>>
> Switch ports are assigned types as defined here. This is important
> as, for example, only ports of the type peering or undefined are
> offered as an option when assigning a port to a physical interface. 
> """
> It led me to believe only peering would be selectable in the menu,
> and with a large amount of empty ports I ended up REALLY wanting to
> exclude the unassigned as suggested. 
> How is that? 
> —
> Reply to this email directly or view it on GitHub.
>   





--
Rob Lister
rob@lonap.net
LONAP Ltd

**Comment by nickhilliard** [comment]
closed ticket is closed.

if you want a new feature, please click on <new issue>.

**Comment by listerr** [comment]
"Please can somebody check if this breaks the resold port / reseller
functionality?"

Thanks.


On Mon, Jan 19 at 9:42:39 PM, Nick Hilliard wrote:

> closed ticket is closed.
> if you want a new feature, please click on .
> —
> Reply to this email directly or view it on GitHub.
>   





--
Rob Lister
rob@lonap.net
LONAP Ltd

**Comment by listerr** [comment]
Also I have member ports which are of type "Other".

Does the behaviour include only "Peering" or exclude only "Unassigned"
ports?

Rob


On Mon, Jan 19 at 9:42:39 PM, Nick Hilliard wrote:

> closed ticket is closed.
> if you want a new feature, please click on .



--
Rob Lister
rob@lonap.net
LONAP Ltd

**Comment by fooelisa** [comment]
"peering" AND "unassigned" are included, as opposed to what the documentation stated previously. Please note that nothing has been changed in this behavior other than adapting the documentation, the suggested change has ben rolled back ;) 

Cheers
Elisa

**Comment by barryo** [comment]
Just to close this out:

> We have a few where they are technically "Other" 

Not affected by this. .

> Also it may well be worth testing this doesn't break the resold port
> capability as these are set to "Fanout" or some such

Unaffected.

> but I haven't worked out when it gets that particular type.

When assigning the physical interface to the virtual interface.

> Another good feature would be to understand the media type offered by the port (e.g., copper / fibre etc.)

Discussed and agreed in #130

> Also we're offering a range of different wavelength optics / Bidirectional optics and it would be good to record that somewhere the customer can see rather than hidden in the port notes.

Also discussed and agreed in #130.

Locking this issue now as it's closed.

**Pull request merged**
