### PR TITLE
move rfc1997 communities config to neighbour template

### PR DESCRIPTION
**Pull request by listerr**
Move the "`interpret communities off`" option to the neighbor template, rather than repeating this config for every neighbor.

### CODE REVIEW

**Comment by barryo** [comment]
Hey @listerr 

As route servers are one of the most production significant services an IX provides, it's probably best to talk with us before opening PRs to save yourself some time. As a rule, commits that affect router configs are only accepted when the supporting tests and known good configs are also updated and Travis tests passing (see [this directory](https://github.com/inex/IXP-Manager/tree/master/data/travis-ci/known-good)). 

Our experience was that changes to `interpret communities` resets the BGP session. I certainly see the merit in moving it to the template but we'd need tested confirmation that this will not affect BGP sessions. Can you confirm or have you confirmed that? *I don't **imagine** relocating the config element would but, as I say, this needs to be confirmed.

Thanks,
Barry

**Comment by barryo** [comment]
btw @listerr - if you can confirm the above, I'll sort out Travis, etc. But this PR will remain open until we're ready to tag the next release (6.0.1 soon anyway). I don't want to drop a Bird config change into release-v6 without release notes.

**Comment by listerr** [comment]
Hi Barry,

Yes, this does work okay. I am currently in the process of updating all our skins to bring them into line with the V6.0 release, and one of the changes I've spotted between our live route server skin config and the files that ship with the v6 release is that we have `interpret communities off;` set only in `neighbor-template.foil.php` and the v6 release files have it in `neighbors.foil.php `.

In our case, the option in the RS config page for RFC1997 Passthru is not enabled by default (as per release note [5.2.0](https://github.com/inex/IXP-Manager/releases/tag/v5.2.0) ) - Seems it was me that discovered that BIRD bounces all BGP sessions when I applied it for the benefit of one member who needs it. :-S

So, given that we've been running it like this since 2019 no problem and it seems to be not enabled by default, I don't expect it will cause any issues.

Rob

**Comment by listerr** [comment]
Update to this.

Actually on closer inspection of our live skin files, was defined in both neighbors.foil.php (not skinned from default with the conditional statement) AND in our skinned neighbor-template.foil.php statically just as "`interpret communities off;`"

The only reason it did not appear in both the template and the neighbour in the config is because we didn't have the rfc1997 passthru option ticked in the RS config pages. So I've ticked that now and done a few tests with our testbed route server that has some live peers on it, just to check if the transition from one config to the other causes sessions to bounce.

My testing shows that moving` interpret communities off;` from the neighbor to the neighbor template and back again does not cause any sessions to bounce.

Rob

**Comment by barryo** [comment]
Double checked on my own test bed and this is indeed hitless.

**Pull request merged**
