### PR TITLE
[NF] Switch to bgpq4

### PR DESCRIPTION
**Pull request by job**
bgpq4 is a fork of bgpq3, aiming to be faster & better.

*Longer description*

- bgpq4 supports the new `IRRd v4` `!a` query, offering some speedup
- there is no `bgpq4` debian package yet, so paths probably are `/usr/local/bin`
- bgpq4 deprecated the '-3' command line option (32-bit ASN support is now enabled by default)

### CODE REVIEW

**Comment by job** [comment]
I signed the code contributor agreement a while back

**Comment by barryo** [comment]
Thanks @job - I'll have a look at this in the new year and see what's an appropriate IXP Manager release to bring it in for.

Happy New Year 🎆

**Comment by job** [comment]
Happy New Year to you too @barryo! 😘

**Comment by barryo** [comment]
Hey @job 

I haven't had a chance to review bgpq4 yet and I haven't seen much noise about it. I'll keep this open and on my list but two things on it:

1. we wouldn't simply s/bgpq3/bgpq4 but rather allow users to choose between them and, if appropriate, eventually deprecate and remove bgpq3. However:
2. if bgpq4 is a drop in replacement, then no code changes required - just point IXP Manager at the bgpq4 binary with the config option:

```
#####################################################
# Utility paths

# See: https://docs.ixpmanager.org/features/irrdb/
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq4
```

**Comment by job** [comment]
@barryo `bgpq4` is intended to be a drop-in replacement indeed

**Comment by barryo** [comment]
Cool, thanks @job. As it stands then, just pointing at the bgpq4 binary will work.

I ahven't had a chance at all to look at v4 so I'll keep this open until I do and see if we should change messaging, etc.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues (open multiple years). 

Where appropriate, will:

1. relocate to the [IDEAS file](https://github.com/inex/IXP-Manager/blob/master/IDEAS).
2. Add additional information below.
3. No relocation / additional information for uber-stale issues.

*Additional information:*

Closing on the basis of:

    if bgpq4 is a drop in replacement, then no code changes required - just point IXP Manager at the bgpq4 binary with the config option:

#####################################################
# Utility paths

# See: https://docs.ixpmanager.org/features/irrdb/
IXP_IRRDB_BGPQ3_PATH=/usr/bin/bgpq4

*Can revisit in the future as a second option.*

**Pull request closed without merging**
