### PR TITLE
[BF] - Wrong login history displayed for user - fixes inex/IXP-Manager#594

### PR DESCRIPTION
**Pull request by yannrobin**
Wrong login history displayed for user

In addition to the above, I have:

 - [x] ensured all relevant template output is escaped to avoid XSS attached with `<?= $t->ee( $data ) ?>` or equivalent.
 - [x] ensured appropriate checks against user privilege / resources accessed
 - [x] API calls (particular for add/edit/delete/toggle) are not implemented with GET and use CSRF tokens to avoid CSRF attacks

### CODE REVIEW

**Comment by listerr** [comment]
This issue seems to still be present in 5.4.1 from the admin panel.

**Comment by barryo** [comment]
@yannrobin  - can you check this and follow up please?

**Comment by barryo** [comment]
In fact I'll reopen inex/IXP-Manager#594 to track.

**Comment by yannrobin** [comment]
@barryo This is working fine on the lasted version. Should I fix it for the version 5.4.1 ?

**Comment by barryo** [comment]
> Should I fix it for the version 5.4.1 ?

No need @yannrobin, thanks. We won't be releasing a 5.4.2 version.

**Pull request merged**
