### PR TITLE
Update templates to use bgp_path.last instead of last_nonaggregated

### PR DESCRIPTION
**Pull request by job**
As per https://bird.network.cz/pipermail/bird-users/2021-February/015199.html
using `roa_check(roa_v4, net, bgp_path.last);` is recommended.

### CODE REVIEW

**Comment by barryo** [comment]
Thanks @job - I have an aging open internal issue on this stemming from:

https://bird.network.cz/pipermail/bird-users/2019-September/013805.html

Memory is somewhat foggy now but at a time, we solved an issue where we were dropping a member's prefixes by using `.last` and they were, oddly, sending an aggregated ASN at the end. Could have been implementation or course. I'll need to find a member doing this here or elsewhere (or just create a text peer) and ensure this won't cause any issues.

Also @job I note we never got you to agree to the CLA - can you see here and sign this for us please: https://docs.ixpmanager.org/dev/cla/

**Comment by job** [comment]
I did the CLA thing in 2017 `[INEX TT# 12605] Re: Job Snijders IXP-Manager CLA`

**Comment by barryo** [comment]
You did indeed @job, apologies. Internal tracking table updated.

**Comment by nickhilliard** [comment]
`last_nonaggregated` was put in because someone decided it would be a great idea to include some internal confed junk at the end of a bunch of prefixes carrying a substantial chunk of traffic.  The relevant spec is section 7.1.8 - 7.1.12 of rfc6907. 

I think it's probably a good idea to use `.last`, but we'd need to test internally first because we would depend on bird implementing rfc6907 correctly which is something that we haven't tested, and we have a small number of prefixes which could potentially be affected by this.  Possibly.

**Comment by barryo** [comment]
## Housekeeping Sept 2021

@barryo closing long running issues.

Where appropriate, will:

* Relocate to the IDEAS file.
* Add additional information below.
* No relocation / additional information for uber-stale issues.

*Additional information: this has been relocated to IDEAs. Similar comments to inex/IXP-Manager#610. NB: Ideas is not where things go to die (check the history of the file). It's where I house keep things that have no short term prospects of implementation. We have plans for OpenBGPd support, etc and all this requires big revisions to how we generate route server configs in IXP Manager. We'll include this in that process.*

**Comment by job** [comment]
I consider this more of a “bugfix” than an “idea”. I’m happy to do the work to rebase this Changeset if that’s appreciated.

**Comment by barryo** [comment]
Thanks Job but I'll pass. The change is easy but we're extremely cautious about a service which we consider uber-critical. For us and the ~170 IXs that use the s/w. We know of some end-networks pushing non-aggregated prefixes and we'll need to look at that. I don't see an urgency here and we will definitely get to it.

**Comment by barryo** [comment]
Also, 'IDEAS' is not meant to be taken literally 😉

**Pull request closed without merging**
